### ISSUE TITLE
求问！mindViewer界面数值代表含义！

### ISSUE THREAD

**Issue by MoonFullx** [JackeyLea/MindViewer#1]
求问啊大大 毕设危机

**Comment by JackeyLea** [comment]
没想到竟然有人看，好长时间没更新了，现在开始把他完成

**Comment by MoonFullx** [comment]
喵喵喵???
加油


------------------
Best Regards！






 




------------------ 原始邮件 ------------------
发件人: "JackeyLea"<notifications@github.com>;
发送时间: 2019年7月3日(星期三) 晚上9:49
收件人: "JackeyLea/MindViewer"<MindViewer@noreply.github.com>;
抄送: "fmx"<648399880@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [JackeyLea/MindViewer] 求问！mindViewer界面数值代表含义！ (#1)




没想到竟然有人看，好长时间没更新了，现在开始把他完成

**Comment by JackeyLea** [comment]
敢问大佬界面用的什么比较方便，我在考虑qchart，qpaint，HTML，暂时先用qpainter的吧

**Comment by JackeyLea** [comment]
软件功能已经全部完成
